### ISSUE TITLE
Organizarea WoUSO v10

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/meta#11]
Un nou an, o noua editie WoUSO.
Organizatori: Marius Cotofana (@mariuscoto), Sergiu Weisz (@Sergiu121)

TODO:
- [x] pregatire director drive
- [x] canal slack
- [x] anuntat echipa de continut si dev (mail pentru ajutoare noi)
- [x] deploy la instanta 2016-2017
- [x] adaugat activitate pe hub.rosedu.org
- [x] promovare prin mesaje pe pagina de facebook (WoUSO si ROSEdu)

**Comment by mgax** [comment]
> canal slack

Avem/facem un slack rosedu sau facem un slack pentru proiect?

**Comment by maria** [comment]
> canal slack
> Avem/facem un slack rosedu sau facem un slack pentru proiect?

Avem slack de rosedu, te poti loga cu emailul de @rosedu.org :)

**Comment by mariuscoto** [comment]
Exista un canal public #wouso si unul privat #wouso-content. Daca vreti sa ajutati cu idei de continut, ping me pentru acces la canalul privat.

**Comment by mariuscoto** [comment]
WoUSO v10 is live: https://wouso.cs.pub.ro/2016
