### ISSUE TITLE
Organizare LIF 2016

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/meta#14]
Urmeaza o noua editie LIF, pe **15 octombrie** si trebuie sa incepem pregatirile. Locatia nu a fost determinata inca.

Director [LIF 2016](https://drive.google.com/drive/folders/0B-lkiy1284rETExDLUFzNnFrbmc?usp=sharing)

TODO:
- [x] stabilirea unui organizator principal
- [x] adaugat event in hub.rosedu.org
- [x] mail catre persoanele care au ajutat in editia trecuta
- [x] call for help pe lista de membrii
- [x] pus la punct un document cu sarcini
  - [x] buget
  - [x] activitati
  - [x] actualizare site
- [x] call for help pe lista generala
- [x] colaborare cu asistentii USO
- [x] intocmit raport de achizitie

**Comment by iulianR** [comment]
Am vorbit cu Marius și o să mă ocup eu de organizare. O să trimit un mail cu un Call for Help în zilele ce urmează.

**Comment by mariuscoto** [comment]
Am actualizat lista de sarcini. Sa ne spui daca ai nevoie de resurse la care nu ai acces.

**Comment by mariuscoto** [comment]
GG!
