### ISSUE TITLE
Creat documentatie pentru sistemul de task-uri

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/meta#6]
Propunere pentru folosirea GitHub Issues pentru task-urile asociatiei.

TODO:
- [x] pagina de wiki descriptiva
- [x] email pe lista pentru review

**Comment by mgax** [comment]
Sună interesant. Poți să dai câteva exemple de issue-uri pe care le-ai vedea aici?

**Comment by mariuscoto** [comment]
@mgax [exemple](https://github.com/rosedu/meta/issues?utf8=%E2%9C%93&q=is%3Aissue) sunt issue-urile care exista deja pe acest repo. Revin cu mai multe detalii odata ce compun pagina de wiki si o sa las un link aici si pe mail.

**Comment by mariuscoto** [comment]
@mgax pagina este [aici](https://github.com/rosedu/meta/wiki/Sarcini-%C3%AEn-cadrul-asocia%C8%9Biei). Ce parere ai ?

**Comment by mgax** [comment]
> Ce parere ai ?

I like, face sens. Hai să vedem dacă reușim să-l folosim consecvent.
